[BUGFIX] Throw exception for requests in broken test environment
`Shopware\Core\Framework\Test\TestCaseBase\SalesChannelApiTestBehaviour`
now throws an exception in case the request done in
`assignSalesChannelContext()` is erroneous in case the test setup is
broken, e.g. due to an invalid .env.test file.

Previously the stacktrace looked as follows and hid the cause of a
failing test:

```
ErrorException: Notice: Undefined index: token

vendor/shopware/core/Framework/Test/TestCaseBase/SalesChannelApiTestBehaviour.php:289
```